#!/usr/bin/env python3
"""
Pod 5 — Digital Product Generator (PDF Guides, Planners, Templates).

Uses WeasyPrint + Jinja2 to convert content briefs into beautifully styled
PDF digital products for Gumroad, Etsy, and Whop.

Falls back to simple HTML→text PDF if WeasyPrint is not installed.

Usage:
    python scripts/digital_product_generator.py [--brief-id 1] [--type pdf_guide]
"""
from __future__ import annotations

import json
import os
import sys
import argparse
from datetime import datetime
from typing import Any

from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from scripts.utils import database as db
from scripts.utils.logger import setup_logger

logger = setup_logger("digital_product_generator")

OUTPUT_DIR = os.environ.get("DIGITAL_PRODUCTS_DIR", "data/digital_products")


# ─── HTML Templates (Jinja2-style, inlined) ──────────────────────────────────
GUIDE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @page {{ size: A4; margin: 2.5cm; }}
  body {{ font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
         color: #1a1a1a; line-height: 1.7; font-size: 13px; }}
  .cover {{ text-align: center; padding: 120px 40px 60px; page-break-after: always; }}
  .cover h1 {{ font-size: 36px; font-weight: 800; color: #0f172a;
               margin-bottom: 12px; letter-spacing: -0.5px; }}
  .cover .subtitle {{ font-size: 16px; color: #64748b; margin-bottom: 40px; }}
  .cover .brand {{ font-size: 12px; color: #94a3b8; margin-top: 80px; }}
  h2 {{ font-size: 20px; color: #1e3a5f; border-bottom: 2px solid #e2e8f0;
        padding-bottom: 6px; margin-top: 32px; }}
  h3 {{ font-size: 16px; color: #334155; margin-top: 24px; }}
  .hook {{ background: #f0f9ff; border-left: 4px solid #3b82f6;
           padding: 14px 18px; margin: 20px 0; font-style: italic;
           border-radius: 0 8px 8px 0; color: #1e40af; }}
  .section {{ margin-bottom: 24px; }}
  .meta {{ font-size: 11px; color: #94a3b8; margin-top: 4px; }}
  .footer {{ text-align: center; font-size: 10px; color: #94a3b8;
             margin-top: 60px; border-top: 1px solid #e2e8f0; padding-top: 12px; }}
  ul {{ padding-left: 20px; }}
  li {{ margin-bottom: 6px; }}
  .monetization {{ background: #f0fdf4; border: 1px solid #bbf7d0;
                   padding: 14px 18px; border-radius: 8px; margin: 20px 0; }}
</style>
</head>
<body>

<div class="cover">
  <h1>{title}</h1>
  <div class="subtitle">{subtitle}</div>
  <div class="brand">Generated by Trend Pulse AI — {date}</div>
</div>

<h2>The Trend</h2>
<div class="hook">{viral_hook}</div>

<div class="section">
  <h3>Target Audience</h3>
  <p>{target_audience}</p>
</div>

<div class="section">
  <h3>Deep Dive</h3>
  {narrative_html}
</div>

<div class="monetization">
  <h3>💰 Monetization Angle</h3>
  <p>{suggested_monetization}</p>
</div>

<div class="section">
  <h3>Key Takeaways</h3>
  <ul>
    {takeaways_html}
  </ul>
</div>

<div class="footer">
  © {year} Trend Pulse — All rights reserved.<br>
  Category: {category} | Virality Score: {virality_score}/100
</div>

</body>
</html>"""


def _narrative_to_html(narrative: str) -> str:
    """Convert plain text narrative to HTML paragraphs."""
    paragraphs = [p.strip() for p in narrative.split("\n") if p.strip()]
    return "\n".join(f"<p>{p}</p>" for p in paragraphs)


def _extract_takeaways(narrative: str) -> list[str]:
    """Extract key sentences from the narrative as takeaways."""
    sentences = [s.strip() for s in narrative.replace("\n", " ").split(".") if len(s.strip()) > 20]
    return sentences[:5]


def generate_pdf_guide(brief: dict, output_path: str | None = None) -> str:
    """
    Generate a styled PDF guide from a content brief.
    Returns the file path of the generated PDF.
    """
    brief_id = brief.get("id", 0)
    title = brief.get("trend_name", "Trend Guide")
    category = brief.get("category_slug") or brief.get("category_name") or "General"
    narrative = brief.get("base_narrative", "")
    takeaways = _extract_takeaways(narrative)

    html = GUIDE_TEMPLATE.format(
        title=title,
        subtitle=f"A comprehensive analysis of the {category} trend everyone is talking about",
        date=datetime.now().strftime("%B %d, %Y"),
        year=datetime.now().year,
        viral_hook=brief.get("viral_hook", ""),
        target_audience=brief.get("target_audience", "General audience"),
        narrative_html=_narrative_to_html(narrative),
        suggested_monetization=brief.get("suggested_monetization", ""),
        takeaways_html="\n".join(f"<li>{t}.</li>" for t in takeaways),
        category=category,
        virality_score=brief.get("virality_score", 0),
    )

    # Output path
    if not output_path:
        safe_title = "".join(c if c.isalnum() or c in " -_" else "" for c in title)[:60].strip()
        safe_title = safe_title.replace(" ", "_").lower()
        output_path = os.path.join(OUTPUT_DIR, f"{safe_title}_brief{brief_id}.pdf")

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Try WeasyPrint first, fall back to simple HTML file
    try:
        from weasyprint import HTML as WeasyprintHTML
        WeasyprintHTML(string=html).write_pdf(output_path)
        logger.info(f"Generated PDF (WeasyPrint): {output_path}")
    except ImportError:
        # Fallback: save as HTML (can be opened in browser and printed to PDF)
        html_path = output_path.replace(".pdf", ".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)
        output_path = html_path
        logger.warning(f"WeasyPrint not installed — saved as HTML: {html_path}")
    except Exception as e:
        # Fallback: save as HTML
        html_path = output_path.replace(".pdf", ".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)
        output_path = html_path
        logger.error(f"WeasyPrint failed ({e}) — saved as HTML: {html_path}")

    return output_path


def save_product(
    brief_id: int,
    product_path: str,
    title: str,
    category: str,
    master_asset_id: int | None = None,
) -> int | None:
    """Save product record to digital_products table."""
    return db.execute_returning(
        """
        INSERT INTO digital_products
            (master_asset_id, product_type, title, file_path, price_usd, platform, status)
        VALUES (%s, 'pdf_guide', %s, %s, 4.99, 'gumroad', 'draft')
        RETURNING id
        """,
        (master_asset_id, title[:500], product_path),
    )


def generate_from_briefs(
    brief_ids: list[int] | None = None,
    categories: list[str] | None = None,
    limit: int = 5,
) -> dict[str, Any]:
    """
    Generate PDF products from content briefs.
    """
    from scripts.genesis_brief_generator import get_actionable_briefs

    if brief_ids:
        placeholders = ",".join(["%s"] * len(brief_ids))
        briefs = db.execute(
            f"""
            SELECT cb.*, gc.slug AS category_slug, gc.display_name AS category_name
            FROM content_briefs cb
            JOIN genesis_categories gc ON cb.category_id = gc.id
            WHERE cb.id IN ({placeholders})
            """,
            tuple(brief_ids),
        )
    else:
        briefs = get_actionable_briefs(categories=categories, limit=limit)

    results = {"generated": 0, "products": []}

    for brief in briefs:
        path = generate_pdf_guide(brief)
        product_id = save_product(
            brief["id"], path,
            brief.get("trend_name", "Guide"),
            brief.get("category_slug", "general"),
        )
        results["generated"] += 1
        results["products"].append({
            "brief_id": brief["id"],
            "product_id": product_id,
            "path": path,
            "title": brief.get("trend_name", ""),
        })

    logger.info(f"Generated {results['generated']} digital products")
    return results


def main(body: dict | None = None, **kwargs) -> dict:
    """Entry point for worker.py integration."""
    if body is None:
        body = kwargs

    brief_ids = body.get("brief_ids")
    categories_raw = body.get("categories")
    limit = int(body.get("limit", 5))

    if isinstance(categories_raw, str):
        categories = [c.strip() for c in categories_raw.split(",")]
    elif isinstance(categories_raw, list):
        categories = categories_raw
    else:
        categories = None

    return generate_from_briefs(
        brief_ids=brief_ids,
        categories=categories,
        limit=limit,
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Digital Product Generator")
    parser.add_argument("--brief-ids", type=str, default=None,
                        help="Comma-separated brief IDs")
    parser.add_argument("--categories", type=str, default=None)
    parser.add_argument("--limit", type=int, default=5)
    args = parser.parse_args()

    brief_ids = [int(x) for x in args.brief_ids.split(",")] if args.brief_ids else None
    cats = [c.strip() for c in args.categories.split(",")] if args.categories else None

    result = generate_from_briefs(brief_ids=brief_ids, categories=cats, limit=args.limit)
    print(json.dumps(result, indent=2, default=str))
